[selection]
save_to_clipboard = true

[window.dimensions]
columns = 128
lines = 32

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
